<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Coupon;

class VoucherSeeder extends Seeder
{
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Coupon::truncate();
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $vouchers = [
            [
                'code'             => 'THLD20',
                'name'             => 'Giảm 20% Chào mừng thành viên mới',
                'type'             => 'percentage',
                'value'            => 20,
                'max_discount'     => 50000,
                'min_order_amount' => 100000,
                'usage_limit'      => 200,
                'used_count'       => 45,
                'starts_at'        => now()->subDays(5),
                'expires_at'       => now()->addDays(25),
                'status'           => 'active',
                'ui_icon'          => 'celebration',
                'theme_class'      => 'coupon-theme-blue',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(59,130,246,0.15), rgba(139,92,246,0.15))',
                'glow_color'       => 'rgba(59,130,246,0.4)',
            ],
            [
                'code'             => 'FREESHIP',
                'name'             => 'Miễn phí vận chuyển toàn quốc',
                'type'             => 'fixed_amount',
                'value'            => 30000,
                'max_discount'     => 30000,
                'min_order_amount' => 150000,
                'usage_limit'      => 500,
                'used_count'       => 120,
                'starts_at'        => now()->subDays(10),
                'expires_at'       => now()->addDays(20),
                'status'           => 'active',
                'ui_icon'          => 'local_shipping',
                'theme_class'      => 'coupon-theme-green',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(16,185,129,0.15), rgba(52,211,153,0.15))',
                'glow_color'       => 'rgba(16,185,129,0.4)',
            ],
            [
                'code'             => 'SACH50K',
                'name'             => 'Giảm 50.000₫ cho đơn từ 300K',
                'type'             => 'fixed_amount',
                'value'            => 50000,
                'max_discount'     => 50000,
                'min_order_amount' => 300000,
                'usage_limit'      => 100,
                'used_count'       => 32,
                'starts_at'        => now()->subDays(3),
                'expires_at'       => now()->addDays(27),
                'status'           => 'active',
                'ui_icon'          => 'savings',
                'theme_class'      => 'coupon-theme-orange',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(245,158,11,0.15), rgba(251,191,36,0.15))',
                'glow_color'       => 'rgba(245,158,11,0.4)',
            ],
            [
                'code'             => 'VIP30',
                'name'             => 'Ưu đãi VIP – Giảm 30%',
                'type'             => 'percentage',
                'value'            => 30,
                'max_discount'     => 100000,
                'min_order_amount' => 500000,
                'usage_limit'      => 50,
                'used_count'       => 8,
                'starts_at'        => now()->subDays(2),
                'expires_at'       => now()->addDays(28),
                'status'           => 'active',
                'ui_icon'          => 'diamond',
                'theme_class'      => 'coupon-theme-purple',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(139,92,246,0.15), rgba(168,85,247,0.15))',
                'glow_color'       => 'rgba(139,92,246,0.4)',
            ],
            [
                'code'             => 'TET2026',
                'name'             => 'Khuyến mãi Tết Nguyên Đán 2026',
                'type'             => 'percentage',
                'value'            => 15,
                'max_discount'     => 80000,
                'min_order_amount' => 200000,
                'usage_limit'      => 1000,
                'used_count'       => 650,
                'starts_at'        => now()->subDays(60),
                'expires_at'       => now()->subDays(30),
                'status'           => 'expired',
                'ui_icon'          => 'park',
                'theme_class'      => 'coupon-theme-red',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(239,68,68,0.15), rgba(248,113,113,0.15))',
                'glow_color'       => 'rgba(239,68,68,0.4)',
            ],
            [
                'code'             => 'HE2026',
                'name'             => 'Khuyến mãi Mùa Hè Rực Rỡ',
                'type'             => 'percentage',
                'value'            => 10,
                'max_discount'     => 40000,
                'min_order_amount' => 200000,
                'usage_limit'      => 300,
                'used_count'       => 150,
                'starts_at'        => now()->subDays(1),
                'expires_at'       => now()->addDays(14),
                'status'           => 'active',
                'ui_icon'          => 'beach_access',
                'theme_class'      => 'coupon-theme-green',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(16,185,129,0.15), rgba(52,211,153,0.15))',
                'glow_color'       => 'rgba(16,185,129,0.4)',
            ],
            [
                'code'             => 'HOCSINH',
                'name'             => 'Giảm 15% cho học sinh - sinh viên',
                'type'             => 'percentage',
                'value'            => 15,
                'max_discount'     => 60000,
                'min_order_amount' => 150000,
                'usage_limit'      => 400,
                'used_count'       => 200,
                'starts_at'        => now()->subDays(10),
                'expires_at'       => now()->addDays(20),
                'status'           => 'active',
                'ui_icon'          => 'school',
                'theme_class'      => 'coupon-theme-blue',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(59,130,246,0.15), rgba(139,92,246,0.15))',
                'glow_color'       => 'rgba(59,130,246,0.4)',
            ],
            [
                'code'             => 'GIAM50K',
                'name'             => 'Giảm ngay 50.000₫ cho đơn hàng mới',
                'type'             => 'fixed_amount',
                'value'            => 50000,
                'max_discount'     => 50000,
                'min_order_amount' => 250000,
                'usage_limit'      => 150,
                'used_count'       => 50,
                'starts_at'        => now()->subDays(2),
                'expires_at'       => now()->addDays(15),
                'status'           => 'active',
                'ui_icon'          => 'card_giftcard',
                'theme_class'      => 'coupon-theme-orange',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(245,158,11,0.15), rgba(251,191,36,0.15))',
                'glow_color'       => 'rgba(245,158,11,0.4)',
            ],
            [
                'code'             => 'SINHNHAT',
                'name'             => 'Mừng sinh nhật - Giảm 25%',
                'type'             => 'percentage',
                'value'            => 25,
                'max_discount'     => 70000,
                'min_order_amount' => 200000,
                'usage_limit'      => 100,
                'used_count'       => 10,
                'starts_at'        => now()->subDays(1),
                'expires_at'       => now()->addDays(6),
                'status'           => 'active',
                'ui_icon'          => 'cake',
                'theme_class'      => 'coupon-theme-purple',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(139,92,246,0.15), rgba(168,85,247,0.15))',
                'glow_color'       => 'rgba(139,92,246,0.4)',
            ],
            [
                'code'             => 'BLACKFRIDAY',
                'name'             => 'Sale Sập Sàn Black Friday',
                'type'             => 'percentage',
                'value'            => 50,
                'max_discount'     => 200000,
                'min_order_amount' => 500000,
                'usage_limit'      => 1000,
                'used_count'       => 1000,
                'starts_at'        => now()->subDays(120),
                'expires_at'       => now()->subDays(115),
                'status'           => 'expired',
                'ui_icon'          => 'flash_on',
                'theme_class'      => 'coupon-theme-red',
                'overlay_gradient' => 'linear-gradient(135deg, rgba(239,68,68,0.15), rgba(248,113,113,0.15))',
                'glow_color'       => 'rgba(239,68,68,0.4)',
            ],
        ];

        foreach ($vouchers as $v) {
            Coupon::create($v);
        }

        echo "Seeded " . count($vouchers) . " vouchers.\n";
    }
}
